### ISSUE TITLE
Agregar soporte para consultas avanzadas

### ISSUE THREAD

**Issue by francisbrito** [developersdo/dev-dom-skills-ws#11]
Por ejemplo:

```
/api/category/where?skills_count_gte=20
/api/developer/where?name=Melvyn%20Perez
/api/skills/where?votes_lt=200
```

**Comment by carlosvasquez** [comment]
Podemos separar la búsqueda por nombre completo en nombre y apellido también; o sea:

**Buscando developers por nombre y apellido**

<pre>
/api/developer/where?first_name=Melvyn
/api/developer/where?last_name_name=Perez
/api/developer/where?complete_name=Melvyn%20Perez
</pre>

_mmm... gt = great that? lt = lower that?_

Pudiera agregarse, `/api/developer/where?votes_gt=10` y `/api/developer/where?votes_lt=200`

Es algo como un top que te gustaría que se logre? Pudiera ser:

**Top X**

<pre>
/api/developer/skills/top/{limit} //sorteado de mayor a menor por los skills
/api/developer/name/top/{limit}/sort/{sort} 
</pre>

_//top de developer según `{limit}` por nombre y `{sort}` asc o desc_

**y se pudiera hacer la combinación de parámetros**

/api/developer/where?first_name=Melvyn&last_name=Perez

/api/developer/where?last_name=Perez&votes_gt=100
- _votes_gt = votos mayores qué_ //votes = skills 
- _votes_lt = votos menores qué_

**Comment by francisbrito** [comment]
:+1:

Eso es precisamente lo que busco!

En definitiva, la inclusión de esos cambios permitiría desarrollar aplicaciones que puedan mostrar la data de manera creativa (gráficos de pie, listados, grafos, etc.)

**Comment by carlosvasquez** [comment]
Ya están unos cuantos hechos 
- http://skills-devdom.herokuapp.com/api/developer/where?first_name=Melvyn
- http://skills-devdom.herokuapp.com/api/developer/where?last_name=P
- http://skills-devdom.herokuapp.com/api/developer/where?sort=asc
- http://skills-devdom.herokuapp.com/api/developer/where?limit=5
- http://skills-devdom.herokuapp.com/api/developer/where?first_name=Melvyn&last_name=P
- http://skills-devdom.herokuapp.com/api/developer/where?first_name=Melvyn&amp;last_name=P
- http://skills-devdom.herokuapp.com/api/developer/where?first_name=M&last_name=P&amp;sort=asc&amp;limit=5
